# Generated by Django 4.0.5 on 2022-06-14 13:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.CharField(max_length=200, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Queued'), (2, 'Processing'), (3, 'Success'), (4, 'Failure'), (5, 'Timeout')], default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('configuration', models.TextField()),
                ('meta', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.device')),
            ],
        ),
    ]
